const accessToken = 'pk.eyJ1IjoiZXJpY2ZhbjI0IiwiYSI6ImNrcHhlY3dsajIzbXQydnFjZGd3ZWR0MWkifQ.2UHQDJPhlp5Cx423H0MQOg';

function init() {
  // console.log(__filename)

  const mymap = L.map('map').setView([33.75073586489209, -84.38624307023588], 12);

  L.tileLayer('https://api.mapbox.com/styles/v1/{username}/{id}/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoibmV3c2FwcHNhamMiLCJhIjoiM0pwTWxXRSJ9.JhYadcrZzpnUf-gX_PItAQ', {
      attribution: 'Map by <a href="https://www.ajc.com/staff/Eric-Fan/">Eric Fan / AJC</a>, Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 18,
      username: 'newsappsajc',
      id: 'ckrwfiyfy15iq17n3q1k793u7'
      // tileSize: 512,
      // zoomOffset: -1
  }).addTo(mymap);

  data.forEach(item => {
      const abatement = `${ item["DAFC estimated abatement value"] || item["AJC estimate of abatement value if none provided"] }`;
      const redIcon = new L.Icon({
        iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-red.png',
        shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
        iconSize: [25, 41] ,
        iconAnchor: [12, 41],
        popupAnchor: [1, -34],
        shadowSize: [41, 41]
      });
      const marker = L.marker([item.Latitude, item.Longitude], {icon: redIcon}).addTo(mymap);
      marker.bindPopup(`${item["Project Owner/Name"]}<br>Estimated abatement value: ${ formatter.format(abatement)}`);
  })

  $.getJSON("Tax_Allocation_District.geojson", function(shapes){
    const geojson = L.geoJson(shapes, {
      style: geoJsonStyle,
      onEachFeature: onEachFeature
    }).addTo(mymap);

    function onEachFeature(feature, layer) {
      layer.bindPopup(`Tax Allocation District - ${feature.properties.ZONEDESC}`);
      layer.on({
          mouseover: highlightFeature,
          mouseout: resetHighlight  
      });
    }

    function highlightFeature(e) {
      let layer = e.target;
  
      layer.setStyle({
          weight: 1,
          color: '#666',
          dashArray: '',
          fillOpacity: 0.7
      });
  
      if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
          layer.bringToFront();
      }
    }

    function resetHighlight(e) {
      geojson.resetStyle(e.target);
    }

    function geoJsonStyle(feature) {
      return {
          fillColor: getColor(feature.properties.ZONEDESC),
          weight: 1,
          opacity: 1,
          color: 'white',
          dashArray: '3',
          fillOpacity: 0.8
      };
    }

    function getColor(ZONEDESC) {
      return ZONEDESC == "Westside" ? '#d9d9d9' :
             ZONEDESC == "Perry/Bolton"  ? '#8dd3c7' :
             ZONEDESC == "Eastside"  ? '#ffffb3' :
             ZONEDESC == "Atlantic Station"  ? '#bebada' :
             ZONEDESC == "Princeton Lakes"   ? '#fb8072' :
             ZONEDESC == "Beltline"   ? '#80b1d3' :
             ZONEDESC == "Metropolitan Pkwy"   ? '#b3de69' :
             ZONEDESC == "Stadium"   ? '#fccde5' :
             ZONEDESC == "Hollowell / Martin Luther King"   ? '#fdb462' :
             ZONEDESC == "Campbellton"   ? '#bc80bd' :
                        'red';
      
      // return ZONEDESC == "Westside" ? '#fdbf6f' :
      // ZONEDESC == "Perry/Bolton"  ? '#fb9a99' :
      // ZONEDESC == "Eastside"  ? '#33a02c' :
      // ZONEDESC == "Atlantic Station"  ? '#b2df8a' :
      // ZONEDESC == "Princeton Lakes"   ? '#a6cee3' :
      // ZONEDESC == "Beltline"   ? '#1f78b4' :
      // ZONEDESC == "Metropolitan Pkwy"   ? '#e31a1c' :
      // ZONEDESC == "Stadium"   ? '#ff7f00' :
      // ZONEDESC == "Hollowell / Martin Luther King"   ? '#cab2d6' :
      // ZONEDESC == "Campbellton"   ? '#6a3d9a' :
      //             'red';                  
    }
    let legend = L.control({position: 'bottomright'});

    legend.onAdd = function (mymap) {
  
      let div = L.DomUtil.create('div', 'legend'),
        categories = ["Westside","Perry/Bolton","Eastside","Atlantic Station","Princeton Lakes","Beltline","Metropolitan Pkwy","Stadium","Hollowell / Martin Luther King","Campbellton"],
        labels = ['<strong>Tax Allocation Districts</strong>'];
  
      for (let i = 0; i < categories.length; i++) {
        labels.push(
          '<i class="legendCircle" style="background:' + getColor(categories[i]) + '"></i> ' + (categories[i] ? categories[i] : '+')
        );
  
      div.innerHTML = labels.join('<br>');
      };
      return div;
    }
    legend.addTo(mymap);
  });
}

const formatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 0
});

const data = [
  {
    "Year": 2018,
    "Date of initial or final approval": "1/23/2018",
    "Project Owner/Name": "T3 -- T3 AS Investors (Hines)",
    "Address": "383 17th Street",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Office",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 84000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 3780000,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 2000,
    "Claimed industrial jobs spec": "",
    "TAD": "Atlantic Station",
    "CID": "No",
    "Status": "Final resolution",
    "Other": "T3 is a 230,000 sf timber-framed office building built on spec",
    "Approval": "Unanimous",
    "Latitude": 33.791387,
    "Longitude": -84.399868,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "1/23/2018",
    "Project Owner/Name": "AMLI Oak Valley -- PPF AMLI Oak Valley Road LLC",
    "Address": "3460 Kingsboro Rd NE",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Apartments",
    "Workforce Units": "None Listed",
    "Affordable Units": "None listed",
    "Bond Value": 45000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 1890000,
    "Est. Full-time jobs created if for a tenant": 28,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final resolution",
    "Other": "Phase 2 of project. 660 apartments. First phase was 640 apartments",
    "Approval": "Unanimous",
    "Latitude": 33.848563,
    "Longitude": -84.356205,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "1/23/2018",
    "Project Owner/Name": "Hyatt Place -- HP Centennial Park JV",
    "Address": "300 Luckie Street",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Garner",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 48000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 2208000,
    "Est. Full-time jobs created if for a tenant": 85,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Westside",
    "CID": "Downtown",
    "Status": "Final resolution",
    "Other": "Hyatt Place Hotel downtown, 174 guest rooms",
    "Approval": "Unanimous",
    "Latitude": 33.762514,
    "Longitude": -84.396008,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "2/27/2018",
    "Project Owner/Name": "Hilton Alpharetta at Windward Parkway -- Chartwell Hospitality",
    "Address": "5775 Windward Parkway",
    "City": "Alpharetta",
    "State": "GA",
    "Commission District": "1-Hausmann",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 65000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 2990000,
    "Est. Full-time jobs created if for a tenant": 200,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final March 2018",
    "Other": "A 249-key business hotel and access road with infrastructure improvements. Nash cited demand for more conference space in Alpharetta.",
    "Approval": "Unanimous",
    "Latitude": 34.087779,
    "Longitude": -84.258427,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "2/27/2018",
    "Project Owner/Name": "395 and 409 Whitehall LLC -- Eagle Environmental",
    "Address": "375 Whitehall Street",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use, residential and retail",
    "Workforce Units": 53,
    "Affordable Units": "None listed",
    "Bond Value": 100000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 4712357,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 31,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final resolution April 2020",
    "Other": "Project is in a brownfield site near the Garnett MARTA station. Final resolution states the project will have 356 residences, including 53 workforce units at 80% AMI, commercial/retail space.",
    "Approval": "Unanimous",
    "Latitude": 33.74590101,
    "Longitude": -84.40032149,
    "Accuracy Score": 0.8,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "2/27/2018",
    "Project Owner/Name": "1150 Spring --Greenstone Ventures --1150 GS Green LLC",
    "Address": "1150 Spring Street",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Office",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 120000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 5400000,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 1000,
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "Midtown",
    "Status": "Final resolution June 2019",
    "Other": "Spec office building across from the Midtown Arts Center Station to be completed in 2021.",
    "Approval": "Unanimous",
    "Latitude": 33.785912,
    "Longitude": -84.389862,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "2/27/2018",
    "Project Owner/Name": "Parkway West Commerce Center -- US Industrial Club IV Enterprises (Hillwood)",
    "Address": "S. Fulton Parkway at Highway 92",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 32000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 1350400,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 400,
    "TAD": "No",
    "CID": "No",
    "Status": "Final resolution May 2018",
    "Other": "572,000 sf warehouse. Site would have a 13-acre park (to be donated to Union City per May 2018 minutes), trails and some retail. Bonds started at $30 million, ended up at $32 million",
    "Approval": "Unanimous",
    "Latitude": 33.6106547306837,
    "Longitude": -84.61100661566091,
    "Accuracy Score": 1,
    "Accuracy Type": "street_center"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "3/27/2018",
    "Project Owner/Name": "Union City Storage LLC",
    "Address": "4700 Jonesboro Road",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Storage facility, hotel, restaurants",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 15500000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 654100,
    "Est. Full-time jobs created if for a tenant": 80,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Union City",
    "CID": "No",
    "Status": "Final Resolution December 2019",
    "Other": "Initially approved at $24,000,000, the project was given final approval at $15.5 million. Initial project said 46 jobs, increased to 80 jobs upon assignment. The project turned an old Walmart into a self-storage facility and included a limited-service hotel, a LongHorn Steakhouse and a fast-casual restaurant",
    "Approval": "Unanimous",
    "Latitude": 33.569286,
    "Longitude": -84.541422,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "4/12/2018",
    "Project Owner/Name": "Pad on Harvard -- HJ Russell & Company",
    "Address": "1777 Harvard Avenue",
    "City": "College Park",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Apartments",
    "Workforce Units": "None Listed",
    "Affordable Units": "None listed",
    "Bond Value": 14000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 588000,
    "Est. Full-time jobs created if for a tenant": 3,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "College Park",
    "CID": "Airport West",
    "Status": "Final Resolution May 2018",
    "Other": "First luxury mid-rise apartments in College Park in 40 years. 109 apartments targeting pilots, flight attendants, airport professionals and Woodward Academy. Project was nearly completed.  when the incentives were initally granted. Russell was leasing 8 to 9 leases per month at the time they granted initial approval. On 4/24/2018, minutes state that the incentive was needed to complete additional phases. Occupancy was 92% and leasing was at 96.5%.",
    "Approval": "Unanimous",
    "Latitude": 33.653534,
    "Longitude": -84.447026,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "4/24/2018",
    "Project Owner/Name": "Alexan 8 West --Trammell Crow Residential",
    "Address": "644 Eighth Street NW",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Apartments",
    "Workforce Units": "None Listed",
    "Affordable Units": "None listed",
    "Bond Value": 70000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 2940000,
    "Est. Full-time jobs created if for a tenant": 6,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "Westside",
    "Status": "Final Resolution October 2018",
    "Other": "270 to 280 apartments and 2,000 sf of retail at Northside and Eighth Street",
    "Approval": "Unanimous",
    "Latitude": 33.779462,
    "Longitude": -84.408714,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "4/24/2018",
    "Project Owner/Name": "Boundary-Peachtree -- Parkside Partners",
    "Address": "1389 Peachtree Street",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Office",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 62000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 2790000,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 600,
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "Midtown",
    "Status": "Final Resolution November 2018",
    "Other": "Redevelopment of three existing office buildings for 160,000 sf of creative Class A office space. Bonds were initially $52 million, increased to $62 million. WeWork is now one of the tenants",
    "Approval": "Unanimous",
    "Latitude": 33.792643,
    "Longitude": -84.386205,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "5/22/2018",
    "Project Owner/Name": "Atlantic Yards --Hines",
    "Address": "170 17th Street NW",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Office",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 205000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 9225000,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 3000,
    "Claimed industrial jobs spec": "",
    "TAD": "Atlantic Station",
    "CID": "No",
    "Status": "Final Resolution December 2019",
    "Other": "More than 500,000 sf of Class AA office in two buildings. Microsoft becomes the eventual anchor tenant.",
    "Approval": "Unanimous",
    "Latitude": 33.79098106431308, 
    "Longitude": -84.39423302658474,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "5/22/2018",
    "Project Owner/Name": "The Met -- BigMet Project Owner LLC/Carter Developments",
    "Address": "680 Murphy Street SW",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South (Beltline)",
    "Project type": "Mixed-use, industrial, retail, creative and residential",
    "Workforce Units": "None Listed",
    "Affordable Units": "None listed",
    "Bond Value": 90000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 4185000,
    "Est. Full-time jobs created if for a tenant": 125,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Final Resolution April 2019",
    "Other": "Overhaul of The Met, a 1914-era warehouse built by Asa Candler, into an artisan and makers space. Project will have approximately 30 residences and comply with Atlanta's affordable housing rules of 15% of units at 80% AMI",
    "Approval": "Unanimous",
    "Latitude": 33.736631096299185, 
    "Longitude": -84.41039267975206,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "5/22/2018",
    "Project Owner/Name": "Element and Courtyard by Marriott dual-branded hotel --Noble Hospitality Fund IV-VA Acquisitions, UGP Peachtree",
    "Address": "640 Peachtree Street NW",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 96700000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 4816773,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 100,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "Midtown",
    "Status": "Final Resolution July 2019",
    "Other": "Original inducement was $77 million, increased to $96 million per DAFC master list. The project is a 124-room hotel and 158-room hotel near the North Avenue MARTA station. It will include a independently operated restaurant/bar. Developer acknowledged there are no hotels in the immediate area. Said the Midtown Alliance would require specific architectural detail.",
    "Approval": "Unanimous",
    "Latitude": 33.772153,
    "Longitude": -84.385071,
    "Accuracy Score": 0.87,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "5/22/2018",
    "Project Owner/Name": "Hunter Road Logistics Center -- Hunter Road Investors/Crow Industrial",
    "Address": "4300 Hunter Road",
    "City": "Union City",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 14000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 590800,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 125,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution December 2018",
    "Other": "234,000 sf tilt wall industrial building built on spec. Developer discussed topography issues, lack of sewer and streetscape/sidewalk needs. But also said occupancy of surrounding warehouses is 100%.",
    "Approval": "Unanimous",
    "Latitude": 33.616376,
    "Longitude": -84.542108,
    "Accuracy Score": 0.7,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "6/26/2018",
    "Project Owner/Name": "SCP Harris Road Owner",
    "Address": "8000 Senoia Road",
    "City": "Fairburn",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Apartments",
    "Workforce Units": "None Listed",
    "Affordable Units": "Referenced, but not defined",
    "Bond Value": 38650000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 1623300,
    "Est. Full-time jobs created if for a tenant": 8,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution July 2018",
    "Other": "273-unit or 276-unit apartment building. Referened as both in different places. Rents of $1,000 to $1,600 per month. Affordable units referenced but not specified.",
    "Approval": "Unanimous",
    "Latitude": 33.537683,
    "Longitude": -84.576558,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "6/26/2018",
    "Project Owner/Name": "Chattahoochee Logistics Center -- FILC Inc.",
    "Address": "7055 Campbellton Road SW",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 62500000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2801906,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 250,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution April 2019",
    "Other": "1.1 million sf warehouse targeted for e-commerce. It's a spec project. $4 million in site work before vertical construction.",
    "Approval": "Unanimous",
    "Latitude": 33.693574,
    "Longitude": -84.616895,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "6/26/2018",
    "Project Owner/Name": "Crown Linen LLC",
    "Address": "3000 Logistics Center Drive, Suite 100",
    "City": "Fairburn",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 25000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 1055000,
    "Est. Full-time jobs created if for a tenant": 400,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "South Fulton",
    "Status": "Final Resolution November 2018",
    "Other": "Commercial laundry facility. Crown's attorney said it has five locations in Florida and is looking at a sixth. It will look elsewhere if it cannot get a tax incentive. Project needs $500,000 in site work.",
    "Approval": "Unanimous",
    "Latitude": 33.542874,
    "Longitude": -84.596451,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "7/24/2018",
    "Project Owner/Name": "Hyatt House hotel -- Legacy PDP LLC",
    "Address": "5775 Peachtree Dunwoody Road",
    "City": "Sandy Springs",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 35000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 1610000,
    "Est. Full-time jobs created if for a tenant": 50,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "Perimeter",
    "Status": "Final Resolution July 2018",
    "Other": "Peacthree Dunwoody Pavilion hotel project with 180 rooms at Northside, St. Joseph's and Children's hospitals.",
    "Approval": "Unanimous",
    "Latitude": 33.911597,
    "Longitude": -84.350521,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "7/24/2018",
    "Project Owner/Name": "PSREG Fountains at North Point Owner LLC/Fuqua Acquisitions II",
    "Address": "11070 Alpharetta Highway",
    "City": "Roswell",
    "State": "GA",
    "Commission District": "2-Ellis",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use retail and residential",
    "Workforce Units": "None Listed",
    "Affordable Units": "None listed",
    "Bond Value": 65000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 3022500,
    "Est. Full-time jobs created if for a tenant": 200,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution july 2018",
    "Other": "18 acre redevelopment of existing project for 70,000 sf of retail, restaurants, entertainment and 300 apartments",
    "Approval": "Unanimous",
    "Latitude": 34.051851,
    "Longitude": -84.334559,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "7/24/2018",
    "Project Owner/Name": "Majestic Airport Center V LLC",
    "Address": "Stonewall Tell Road at South Fulton Parkway",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 275000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 10980592,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 2000,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution February 2019",
    "Other": "Fifth phase of an airport-area industrial/warehouse development. Tenant not ID'd, this is a speculative project. Developer cited topography challenges and need for a 4,000-foot extension of sewer.",
    "Approval": "Unanimous",
    "Latitude": 33.61910024,
    "Longitude": -84.55971927,
    "Accuracy Score": 0.33,
    "Accuracy Type": "place"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "9/25/2018",
    "Project Owner/Name": "Alcon Laboratories Inc.",
    "Address": "11460 Johns Creek Parkway",
    "City": "Johns Creek",
    "State": "GA",
    "Commission District": "1-Hausmann",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 67000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 2827400,
    "Est. Full-time jobs created if for a tenant": 100,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution September 2018",
    "Other": "Third phase of Alcon's contact lens manufacturing facility. 50 to 100 jobs.",
    "Approval": "Unanimous",
    "Latitude": 34.05519362,
    "Longitude": -84.170693,
    "Accuracy Score": 0.52,
    "Accuracy Type": "street_center"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "9/25/2018",
    "Project Owner/Name": "First Park Fairburn -- First Industrial Realty Trust",
    "Address": "4955 Oakley Industrial Boulevard",
    "City": "Fairburn",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 40000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 1688000,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 800,
    "TAD": "No",
    "CID": "South Fulton",
    "Status": "Final Resolution September 2018",
    "Other": "Speculative warehouse and distribution facility of up to 960,000 sf. Claimed 800 full time jobs.",
    "Approval": "Unanimous",
    "Latitude": 33.54931515,
    "Longitude": -84.54880662,
    "Accuracy Score": 0.6,
    "Accuracy Type": "nearest_rooftop_match"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "10/19/2018",
    "Project Owner/Name": "8 West Holdings LLC",
    "Address": "Howell Mill Road at Eighth Street",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Mixed-use, office, retail and residential",
    "Workforce Units": 42,
    "Affordable Units": "None",
    "Bond Value": 55000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 2557500,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 900,
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "Westside",
    "Status": "Final Resolution October 2018",
    "Other": "Mixed-use office, retail and residential. 200,000 sf of office and retail with 15,000 sf of existing retail. Project will also contain 270 to 285 apartments, 15 percent at 80 percent AMI.",
    "Approval": "Unanimous",
    "Latitude": 33.779657,
    "Longitude": -84.410232,
    "Accuracy Score": 0.8,
    "Accuracy Type": "intersection"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "10/19/2018",
    "Project Owner/Name": "Westside Village Atlanta -- Eden Rock Real Estate Partners",
    "Address": "2260 Marietta Boulevard",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Garner",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use residential, retail and restaurant",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 30000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 1395000,
    "Est. Full-time jobs created if for a tenant": 50,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Perry-Bolton",
    "CID": "No",
    "Status": "Final Resolution in November 2018",
    "Other": "Tear down of existing warehouse and residences for 19 townhomes, 90,000 sf of retail and restaurant space to create 50 new full time jobs and 200 part time jobs. Developer cited demolition and remediation costs. Mr. Ashkouti emphasized that the incentive is required to proceed with the project as presented and that without the incetnive they would have to pause development and look for exit strategies. ...(he) stated that since five acres of the project would not be conducinve for development without the incentive, that portion of the property would not be developed resulting in the retail portion being comprised of lower quality retail. Mr. Ashkouti explained that scaling back the project in this manner is certainly not what the neighborhood has requested and would signficantly set back growth in the area.",
    "Approval": "Unanimous",
    "Latitude": 33.817249,
    "Longitude": -84.448621,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "10/19/2018",
    "Project Owner/Name": "Oakmont 85 South II -- PME Oakmont Goodson II LLC",
    "Address": "7050 Goodson Road",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 21000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 886200,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 50,
    "TAD": "Union City",
    "CID": "No",
    "Status": "Final Resolution October 2018",
    "Other": "Speculative 384,000 sf warehouse",
    "Approval": "Unanimous",
    "Latitude": 33.563583,
    "Longitude": -84.55008,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "11/13/2018",
    "Project Owner/Name": "Noble AC/Moxy Project -- Noble, NF III Atlanta Midtown",
    "Address": "53 Fourteenth Street NW",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 60000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 2760000,
    "Est. Full-time jobs created if for a tenant": 145,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "Midtown",
    "Status": "Final Resolution November 2018",
    "Other": "Dual-branded hotel, Moxy and AC, by Marriott. 288-rooms between the two hotels. Project was preparing for a January 2019 opening, in just a few months. They got preliminary approval in 2016. Developer said project was not feasible without the incentive.",
    "Approval": "Unanimous",
    "Latitude": 33.78620432,
    "Longitude": -84.38582485,
    "Accuracy Score": 0.33,
    "Accuracy Type": "place"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "11/13/2018",
    "Project Owner/Name": "Phipps Plaza mixed-use --Peachtree Phipps LLC/Simon Property Group",
    "Address": "3500 Peachtree Road",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use, office, hotel and retail",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 216200000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 10053300,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 1650,
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "Buckhead",
    "Status": "Final Resolution November 2018",
    "Other": "Redevelopment of the former Belk store at Phipps Plaza, including an office tower, fitness center, Nobu hotel and restaurants. Site also would include a replacement fire station for Atlanta Fire & Rescue. Phipps' representative said Simon can choose where to invest, and Phipps got the project because of the incentive.",
    "Approval": "Unanimous",
    "Latitude": 33.852944,
    "Longitude": -84.360615,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "11/13/2018",
    "Project Owner/Name": "Graham Logistics Center Phase I -- Stream Realty, SRPF and A/Graham Road Industrial",
    "Address": "7375 Graham Drive",
    "City": "Fairburn",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 18600000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 784920,
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 350,
    "TAD": "No",
    "CID": "Oakley",
    "Status": "Final Resolution December 2018",
    "Other": "Two speculative industrial buildings. Site has challenging topography, totaling $5 million in rock blasting and other costs.",
    "Approval": "Unanimous",
    "Latitude": 33.560069,
    "Longitude": -84.537349,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "11/13/2018",
    "Project Owner/Name": "Graham Logistics Center Phase II -- Stream Realty",
    "Address": "Oakley Road at Jonesboro Road",
    "City": "Fairburn",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 19250000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 350,
    "TAD": "No",
    "CID": "Oakley",
    "Status": "Pending",
    "Other": "Phase 2 of the project",
    "Approval": "Unanimous initial approval",
    "Latitude": 33.566972,
    "Longitude": -84.532801,
    "Accuracy Score": 0.79,
    "Accuracy Type": "intersection"
  },
  {
    "Year": 2018,
    "Date of initial or final approval": "12/4/2018",
    "Project Owner/Name": "Majestic Realty (DHL facility)",
    "Address": "4505 Derrick Industrial Parkway",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 60000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2493133,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 600,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution February 2019",
    "Other": "500,000 sf speculative e-commerce distribution facility that appears to be occupied by DHL. Initially 350 jobs, raised to 600 jobs. Minutes cite severe topography challenges, need for sewer and traffic lights.",
    "Approval": "Unanimous",
    "Latitude": 33.62913,
    "Longitude": -84.582724,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "1/22/2019",
    "Project Owner/Name": "982 URPDC LLC Urban Realty Partners and Prestwick Development",
    "Address": "982 Memorial Drive",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Apartments",
    "Workforce Units": 56,
    "Affordable Units": "None",
    "Bond Value": 41650000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1982946,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 5,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Final Resolution January 2019",
    "Other": "205 apartments, including 56 \"roommate\" units that are deemed workforce housing at 85 percent AMI",
    "Approval": "One opposed Carstarphen",
    "Latitude": 33.746832,
    "Longitude": -84.355163,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "1/22/2019",
    "Project Owner/Name": "Aspire --CRP/Lincoln Property Group",
    "Address": "900 Joseph E. Lowery Boulevard",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Apartments",
    "Workforce Units": "N/A",
    "Affordable Units": 26,
    "Bond Value": 33000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 1386000,
    "Est. Full-time jobs created if for a tenant": 5,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Final Resolution February 2019",
    "Other": "171-unit apartment building in Beltline TAD with 15% of units reserved for people making 80% of AMI.",
    "Approval": "Unanimous",
    "Latitude": 33.778587,
    "Longitude": -84.417484,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "1/22/2019",
    "Project Owner/Name": "Star Metals -- Allen Morris Company",
    "Address": "1034 Howell Mill Road",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Mixed-use, office, hotel, retail and residential",
    "Workforce Units": 47,
    "Affordable Units": "None",
    "Bond Value": 330000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 16692285,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 500,
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Final Resolution January 2019",
    "Other": "500 full time jobs per master list. 185,000 sf of Class A office, retail and 409 apartments",
    "Approval": "One opposed Carstarphen",
    "Latitude": 33.782902,
    "Longitude": -84.411802,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "1/22/2019",
    "Project Owner/Name": "Fairfield Southside Trail -- FF Realty IV",
    "Address": "125 Milton Avenue SW",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South (Beltline)",
    "Project type": "Apartments",
    "Workforce Units": 47,
    "Affordable Units": "None",
    "Bond Value": 58000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2619579,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 7,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Final Resolution February 2019",
    "Other": "310-unit apartment building, 15% of units reserved for people making 80 percent AMI.",
    "Approval": "Unanimous",
    "Latitude": 33.721586,
    "Longitude": -84.384778,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "1/22/2019",
    "Project Owner/Name": "Midtown Union (fka Midtown Heights) -- MetLife",
    "Address": "17th Street at West Peachtree Street",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use office, retail and hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 1101000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 57563608,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 2735,
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "Midtown",
    "Status": "Final Resolution Phase I November 2019",
    "Other": "Two phases. First will have a 500,000 sf Class A office tower, retail and a hotel. Invesco later committed to the site. Second phase will have 1.4 million sf office space",
    "Approval": "Two opposed Bacote and Carstarphen",
    "Latitude": 33.792030062727505, 
    "Longitude": -84.38775624268244,
    "Accuracy Score": 0.8,
    "Accuracy Type": "intersection"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "1/22/2019",
    "Project Owner/Name": "1105 West Peachtree -- SEI 1105 West Peachtree/Selig Enterprises",
    "Address": "1105 West Peachtree Street",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use, office, hotel, retail and residential",
    "Workforce Units": "",
    "Affordable Units": "",
    "Bond Value": 303000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 16043768,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 4700,
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "Midtown",
    "Status": "Final Resolution June 2019",
    "Other": "665,000 sf Class A office that was later leased to Google and Smith Gambrell & Russell, retail, 178-room hotel",
    "Approval": "One opposed Carstarphen",
    "Latitude": 33.7848293,
    "Longitude": -84.38740846,
    "Accuracy Score": 0.87,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "2/26/2019",
    "Project Owner/Name": "Atlanta Dairies II -- WP South Acquisitions/Wood Partners",
    "Address": "777 Memorial Drive SE",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Apartments",
    "Workforce Units": 38,
    "Affordable Units": "N/A",
    "Bond Value": 57500000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2608732,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 45,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Final Resolution March 2019",
    "Other": "A 250-unit apartment complex with 38 workforce units at 80% AMI",
    "Approval": "One opposed Carstarphen",
    "Latitude": 33.746486,
    "Longitude": -84.361767,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "2/26/2019",
    "Project Owner/Name": "Ross Hotel Partners -- WLKR Ponce Owner LLC",
    "Address": "551 Ponce de Leon Avenue",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 20000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 866998,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 58,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Final Resolution March 2019",
    "Other": "112-room boutique Hyatt hotel, restaurant, retail space and parking near Ponce City Market.",
    "Approval": "One opposed Carstarphen",
    "Latitude": 33.773213,
    "Longitude": -84.368891,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "2/26/2019",
    "Project Owner/Name": "PVH Corp (Project Wide Open)",
    "Address": "8500 Tatum Road",
    "City": "Palmetto",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 75700000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2169660,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 575,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution April 2019",
    "Other": "Automated distribution center for the maker of Calvin Klein and other brands.",
    "Approval": "Unanimous",
    "Latitude": 33.527285,
    "Longitude": -84.637727,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "2/26/2019",
    "Project Owner/Name": "US Industrial Club IV Enterprises/Hillwood",
    "Address": "6900 Goodson Road",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 30000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1473483,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 400,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution October 2019",
    "Other": "",
    "Approval": "Unanimous",
    "Latitude": 33.566895,
    "Longitude": -84.550291,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "3/26/2019",
    "Project Owner/Name": "Pollack Shores Development",
    "Address": "72 Milton Avenue SE",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South (Beltline)",
    "Project type": "Apartments and townhomes",
    "Workforce Units": 42,
    "Affordable Units": "None",
    "Bond Value": 60000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": "",
    "AJC estimate of abatement value if none provided": 2520000,
    "Est. Full-time jobs created if for a tenant": 8,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Final Resolution-September 2019 ($60,000,000)",
    "Other": "270 apartments and 103 town homes. The tax break is for the apartments. 42 units at 80% AMI. Original bond was $48 million, increased to $60 million. Original tax break value was $2,175,400, but estimated a new one based on higher bond amount.",
    "Approval": "Unanimou",
    "Latitude": 33.72374,
    "Longitude": -84.384385,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "3/26/2019",
    "Project Owner/Name": "Southern Post LLC -- SJ Collins Enterprises",
    "Address": "1023 Alpharetta Street",
    "City": "Roswell",
    "State": "GA",
    "Commission District": "2-Ellis",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use, office, retail and residential",
    "Workforce Units": "None Listed",
    "Affordable Units": "None listed",
    "Bond Value": 75000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2750155,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 542,
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution July 2019",
    "Other": "51,000 sf of commercial/retail/restaurant space, 73,000 sf of offices and 128 apartments and 16 townhomes",
    "Approval": "Unanimous",
    "Latitude": 34.027235,
    "Longitude": -84.358323,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "3/26/2019",
    "Project Owner/Name": "DHL Supply Chain -- Exel Inc",
    "Address": "0 Bohannon Road",
    "City": "Fairburn",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 12900000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 578838,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 75,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "South Fulton",
    "Status": "Final Resolution April 2019",
    "Other": "Distribution facility",
    "Approval": "Unanimous",
    "Latitude": 33.548008,
    "Longitude": -84.593518,
    "Accuracy Score": 0.6,
    "Accuracy Type": "street_center"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "3/26/2019",
    "Project Owner/Name": "Mason Road Distibution Center -- Lincoln Property Company/Morgan Stanley",
    "Address": "Mason Road and Hunter Road",
    "City": "Union City",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 25000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1227903,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 448,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution June 2019",
    "Other": "Warehouse on 30 acres of property. Speculative. Developer cites need for overcoming challenging topography and need for two retention ponds and a 140 culvert bridge over Wolf Creek",
    "Approval": "Unanimous",
    "Latitude": 33.618961,
    "Longitude": -84.544339,
    "Accuracy Score": 0.8,
    "Accuracy Type": "intersection"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "3/26/2019",
    "Project Owner/Name": "Union 85 Distribution Center -- Lincoln Property Company/Morgan Stanley",
    "Address": "3725 Royal South Parkway",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 15280000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1978575,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 271,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution June 2019",
    "Other": "Distribution facility on 25.27 acres.",
    "Approval": "Unanimous",
    "Latitude": 33.59030944,
    "Longitude": -84.51141763,
    "Accuracy Score": 0.33,
    "Accuracy Type": "place"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "4/23/2019",
    "Project Owner/Name": "CHI Acquisitions LP",
    "Address": "Fulton Industrial Boulevard at Westgate Parkway",
    "City": "South Fulton",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 51000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2265094,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 600,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution June 2019",
    "Other": "Speculative industrial park of three builings totaling 870,000 sf on 92 acres.",
    "Approval": "Unanimous",
    "Latitude": 33.70547078,
    "Longitude": -84.59738521,
    "Accuracy Score": 0.8,
    "Accuracy Type": "intersection"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "6/7/2019",
    "Project Owner/Name": "ATL Fairburn JV/Red Rock Developments",
    "Address": "Oakley Industrial Boulevard",
    "City": "Fairburn",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 67000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2785270,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 450,
    "TAD": "No",
    "CID": "South Fulton",
    "Status": "Final Resolution July 2019",
    "Other": "Speculative warehouse buildings totaling 1,110,000 sf of space and 7,000 sf of office space.",
    "Approval": "Unanimous",
    "Latitude": 33.538036,
    "Longitude": -84.568677,
    "Accuracy Score": 1,
    "Accuracy Type": "street_center"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "6/25/2019",
    "Project Owner/Name": "Goat Farm -- Goat Farm Development LLC/ Preston Ridge",
    "Address": "1200 Foster Street",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Mixed-use",
    "Workforce Units": 36,
    "Affordable Units": "None Listed",
    "Bond Value": 55000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2787235,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 8,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "Westside",
    "Status": "Final Resolution July 2019",
    "Other": "Four-story apartment building with 240 units, of which 36 will be at 80% AMI. Also will conntain 50 commercial artist studios.",
    "Approval": "One opposed Tidwell",
    "Latitude": 33.786197,
    "Longitude": -84.416381,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "6/25/2019",
    "Project Owner/Name": "Waldo's Old Fourth Ward -- RCC LLC and Lucror Resources",
    "Address": "40 Boulevard SE",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use office, retail, hotel and residential",
    "Workforce Units": "None Listed",
    "Affordable Units": "None Listed",
    "Bond Value": 80000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 3607373,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 685,
    "Claimed industrial jobs spec": "",
    "TAD": "Eastside",
    "CID": "No",
    "Status": "Final Resolution July 2019",
    "Other": "120,000 sf office building, 125-room hotel, 10 short-term rental townhomes and 10,000 sf retail",
    "Approval": "Unanimous",
    "Latitude": 33.753532,
    "Longitude": -84.371657,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "6/25/2019",
    "Project Owner/Name": "400 Bishop -- 400 Bishop Master LLC",
    "Address": "400 Bishop Street",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use office and retail",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 50000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2277000,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 600,
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution October 2019",
    "Other": "130,000 sf office building with 10,000 sf of retail. Speculative. Pedestrian bridge to connect to Atlantic Station.",
    "Approval": "Unanimous",
    "Latitude": 33.793671,
    "Longitude": -84.400461,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "6/25/2019",
    "Project Owner/Name": "JLB 99 West Paces Ferry -- JLB Partners",
    "Address": "99 West Paces Ferry Road",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use, residential and retail",
    "Workforce Units": "None Listed",
    "Affordable Units": "None listed",
    "Bond Value": 271000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 3355560,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 60,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "Buckhead",
    "Status": "Final Resolution June 2019",
    "Other": "485-apartments and 13,500 sf of retail",
    "Approval": "Two opposed Lamont and Tidwell",
    "Latitude": 33.841226,
    "Longitude": -84.383048,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "6/25/2019",
    "Project Owner/Name": "Crossroads Business Center -- C5I- at Crossroads LLC/Core5 Industrial",
    "Address": "Campbellton Fairburn Road",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 50000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2374790,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 1500,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution July 2019",
    "Other": "1 million sf distribution center for \"high-value inventory.\" Appears speculative.",
    "Approval": "Unanimous",
    "Latitude": 33.602618,
    "Longitude": -84.606646,
    "Accuracy Score": 1,
    "Accuracy Type": "street_center"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "7/23/2019",
    "Project Owner/Name": "Portman O4W Hotel -- Portman Old Fourth Ward",
    "Address": "667 Auburn Avenue",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 80000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 3502937,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 462,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Eastside",
    "CID": "No",
    "Status": "Final Resolution August 2019",
    "Other": "200-room boutique hotel",
    "Approval": "One opposed Tidwell",
    "Latitude": 33.756993,
    "Longitude": -84.366192,
    "Accuracy Score": 0.9,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "8/27/2019",
    "Project Owner/Name": "Sobu Flats",
    "Address": "374 East Paces Ferry Road",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 82300000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 3809600,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 149,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "Buckhead",
    "Status": "Final Resolution September 2019",
    "Other": "Conversion of an 8-story condo buliding into a 216-room boutique hotel with restaurant and meeting space.",
    "Approval": "Four opposed Tidwell, Turpeau, Lamont and Bacote",
    "Latitude": 33.839451,
    "Longitude": -84.374994,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "8/27/2019",
    "Project Owner/Name": "Airport Logistics Center -- SF Parkway I LLC/TPA Group",
    "Address": "Stonewall Tell Road at South Fulton Parkway",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Darnell",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 30000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1458355,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 100,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution September 2019",
    "Other": "500,000 sf industrial building.",
    "Approval": "Unanimous",
    "Latitude": 33.6190184,
    "Longitude": -84.55976236,
    "Accuracy Score": 0.33,
    "Accuracy Type": "place"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "10/22/2019",
    "Project Owner/Name": "Halpern's Steak and Seafood Company",
    "Address": "4685 Welcome All Road",
    "City": "South Fulton",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A/",
    "Affordable Units": "N/A",
    "Bond Value": 27000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1149820,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 46,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution November 2019",
    "Other": "Halpern's .plans to buy building it currently leases, buy 5 acres nearby and expand by 47,000 sf and add 46 new jobs",
    "Approval": "One opposed Tidwell",
    "Latitude": 33.62616731,
    "Longitude": -84.52929703,
    "Accuracy Score": 0.27,
    "Accuracy Type": "place"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "11/19/2019",
    "Project Owner/Name": "Vesta Adams Park LLC",
    "Address": "1991 Delowe Drive SW",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Apartments",
    "Workforce Units": 298,
    "Affordable Units": "None",
    "Bond Value": 30000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1099890,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 5,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution December 2019",
    "Other": "Redevelopment of a 298-unit apartment complex with all workforce units at 67.5%AMI.",
    "Approval": "Unanimous",
    "Latitude": 33.700064,
    "Longitude": -84.460067,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2019,
    "Date of initial or final approval": "11/19/2019",
    "Project Owner/Name": "Vesta Red Oak Apartments -- Vesta Red Oak LLC",
    "Address": "5100 Welcome All Road",
    "City": "South Fulton",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Apartments",
    "Workforce Units": 220,
    "Affordable Units": "None",
    "Bond Value": 19500000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 674736,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 5,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution December 2019",
    "Other": "Redevelopment of vacant and dilapidated apartments into 220 units",
    "Approval": "Unanimous",
    "Latitude": 33.61482323,
    "Longitude": -84.52388254,
    "Accuracy Score": 0.27,
    "Accuracy Type": "place"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "1/28/2020",
    "Project Owner/Name": "The Interlock II -- SJ Collins Enterprises",
    "Address": "1042 Northside Drive",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Mixed-use office, retail and hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 110000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 5498694,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 700,
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "Westside",
    "Status": "Induced January 2020",
    "Other": "58,500 sf of commercial, retail and restaurant space, a grocery store, 115,000 sf of office space, a 190-room dual-branded hotel.",
    "Approval": "One opposed Tidwell",
    "Latitude": 33.783323,
    "Longitude": -84.408167,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "2/25/2020",
    "Project Owner/Name": "680 Hamilton -- TPA Residential",
    "Address": "680 Hamilton Avenue SE",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South (Beltline)",
    "Project type": "Apartments",
    "Workforce Units": 40,
    "Affordable Units": "N/A",
    "Bond Value": 53000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2387136,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 6,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Final Resolution July 2020",
    "Other": "Beltline apartment project with 263 units, 40 workforce units at 80% AMI, developer claims vast deposits of lime.",
    "Approval": "One opposed Tidwell, Lamont abstained",
    "Latitude": 33.7266,
    "Longitude": -84.365394,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "2/25/2020",
    "Project Owner/Name": "Echo Street II -- West Midtown OZ Holdings",
    "Address": "Donald Lee Hollowell Parkway at Northside Drive",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Apartments",
    "Workforce Units": 57,
    "Affordable Units": "N/A",
    "Bond Value": 73000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 3288310,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 8,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Westside",
    "CID": "No",
    "Status": "Final Resolution July 2020",
    "Other": "Apartment project with 285 units, of which 57 will be workforce units at 80% AMI",
    "Approval": "Unanimous but Bacote abstained",
    "Latitude": 33.773348,
    "Longitude": -84.40876316,
    "Accuracy Score": 0.68,
    "Accuracy Type": "intersection"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "2/25/2020",
    "Project Owner/Name": "Echo Street -- West Midtown OZ Holdings",
    "Address": "Donald Lee Hollowell Parkway at Northside Drive",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use of office and retail",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 154000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 6956300,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": 1950,
    "Claimed industrial jobs spec": "",
    "TAD": "Westside",
    "CID": "No",
    "Status": "Final Resolution July 2020",
    "Other": "A mixed-use project including 278,100 sf of office space, 50,700 sf commercial space.",
    "Approval": "Unanimous but Bacote abstained",
    "Latitude": 33.773348,
    "Longitude": -84.40876316,
    "Accuracy Score": 0.68,
    "Accuracy Type": "intersection"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "3/24/2020",
    "Project Owner/Name": "I-285 Exit 12 Commerce Center -- Johnson Development Associates",
    "Address": "Donald Lee Hollowell Parkway at Fulton Industrial Boulevard",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 13600000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 674531,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 200,
    "TAD": "Hollowell",
    "CID": "Fulton Industrial",
    "Status": "Induced March 2020",
    "Other": "Speculative 250,000 sf warehouse for e-commerce or light manufacturing",
    "Approval": "One opposed Tidwell",
    "Latitude": 33.79011848582224, 
    "Longitude": -84.4961347846179,
    "Accuracy Score": 1,
    "Accuracy Type": "street_center"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "3/24/2020",
    "Project Owner/Name": "Airport Logistics Center West -- TPA Group",
    "Address": "Stonewall Tell Road at South Fulton Parkway",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Carn",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 18000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 877486,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 50,
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution April 2020",
    "Other": "Speculative 250,000 sf warehouse.",
    "Approval": "Unanimous",
    "Latitude": 33.61903627,
    "Longitude": -84.55983746,
    "Accuracy Score": 0.33,
    "Accuracy Type": "place"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "4/28/2020",
    "Project Owner/Name": "CF Buffington Apartments LLC",
    "Address": "5740 Buffington Road",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Carn",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Apartments",
    "Workforce Units": "None Listed",
    "Affordable Units": "None listed",
    "Bond Value": 22000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1020014,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 5,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution June 2020",
    "Other": "156-unit apartment and retnal townhome community.",
    "Approval": "One opposed Tidwell",
    "Latitude": 33.597047,
    "Longitude": -84.498052,
    "Accuracy Score": 0.6,
    "Accuracy Type": "street_center"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "4/28/2020",
    "Project Owner/Name": "Project Pie -- Briar Patch Holdings",
    "Address": "Great Southwest Parkway at Fulton Industrial Boulevard",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "6-Carn",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 23275000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1386486,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 162,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution October 2020",
    "Other": "Food processing facility from an unnamed tenant later identified as Briar Patch Holdings. Investment amount downgraded to $23,250,000.",
    "Approval": "Unanimous",
    "Latitude": 33.74498351,
    "Longitude": -84.55960232,
    "Accuracy Score": 0.87,
    "Accuracy Type": "street_center"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "5/19/2020",
    "Project Owner/Name": "Lidl US -- Grocery Store",
    "Address": "690 Holcomb Bridge Road",
    "City": "Roswell",
    "State": "GA",
    "Commission District": "2-Ellis",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Retail",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 14100000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 485314,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 50,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Induced May 2020",
    "Other": "Revelopment of a strip mall into a new grocery store and two standalone restaurants",
    "Approval": "Three opposed Bacote, Lamont and Tidwell",
    "Latitude": 34.033148,
    "Longitude": -84.33996,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "8/25/2020",
    "Project Owner/Name": "Steel Mill Hotel -- Peachtree Hotel Group",
    "Address": "17th Street at Atlantic Drive",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Hotel",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 85500000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 3767319,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 127,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Atlantic Station",
    "CID": "No",
    "Status": "Induced August 2020",
    "Other": "Dual branded Spring Hill Suites and Tapestry hotel. Will have a restaurant and ground floor retail",
    "Approval": "One opposed Tidwell",
    "Latitude": 33.78952,
    "Longitude": -84.40168,
    "Accuracy Score": 1,
    "Accuracy Type": "street_center"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "8/25/2020",
    "Project Owner/Name": "Beltline & Boulevard -- Middle Street Partners",
    "Address": "1015 Boulevard SE",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South (Beltline)",
    "Project type": "Apartments",
    "Workforce Units": 48,
    "Affordable Units": "N/A",
    "Bond Value": 73000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 3286918,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 4,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Induced August 2020",
    "Other": "323 apartments including 48 workforce units at 80% AMI. 5,00 sf retail on the Beltline. Developer cited $6.5 millionin added development costs because of underground parking and topography.",
    "Approval": "Three opposed Turpeau, Lamont and Tidwell",
    "Latitude": 33.726594,
    "Longitude": -84.369513,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "8/25/2020",
    "Project Owner/Name": "Reese Meyer -- Atlantic Capital Properties",
    "Address": "111 John Wesley Dobbs Avenue",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Student housing",
    "Workforce Units": 37,
    "Affordable Units": "N/A",
    "Bond Value": 87250000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 4388258,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 12,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Eastside",
    "CID": "Downtown",
    "Status": "Induced August 2020",
    "Other": "247 student housing units, with 15% of those reserved at 80% AMI -- or 37 units. Said that equates to housing for 111 students at 80% AMI.",
    "Approval": "One opposed Tidwell",
    "Latitude": 33.756833,
    "Longitude": -84.383828,
    "Accuracy Score": 0.78,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "9/22/2020",
    "Project Owner/Name": "Novel West Midtown -- Crescent Communities",
    "Address": "1330 Fairmont Avenue",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Apartments",
    "Workforce Units": 34,
    "Affordable Units": "N/A",
    "Bond Value": 75000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 3382882,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 7,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Induced September 2020",
    "Other": "345-unit apartment project with 34 units reserved for workforce housing at 60% AMI. Project is on a brownfield.",
    "Approval": "Two opposed Lamont and Tidwell",
    "Latitude": 33.791301,
    "Longitude": -84.423398,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "9/22/2020",
    "Project Owner/Name": "Royal Fresh Cuts",
    "Address": "3600 Zip Industrial Boulevard",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 9500000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 417978,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 50,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Induced September 2020",
    "Other": "Expansion of an existing fresh-cut produce and dairy products plant in southeast Atlanta. The plants currently employ 400 workers making $10-15 per hour.",
    "Approval": "Unanimously",
    "Latitude": 33.656716,
    "Longitude": -84.38426,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "11/13/2020",
    "Project Owner/Name": "1246 Allene -- RangeWater Development",
    "Address": "1246 Allene Avenue SW",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "5-Arrington",
    "North I-20/South I-20 or Beltline": "South (Beltline)",
    "Project type": "Apartments",
    "Workforce Units": 49,
    "Affordable Units": "N/A",
    "Bond Value": 55000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2468381,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 11,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Induced November 2020",
    "Other": "Beltline apartment project with 323 units, of which 49 reserved at 80% AMI. Sits on a former battery plant with environmental remediation needed totaling $3.4 million.",
    "Approval": "",
    "Latitude": 33.720668,
    "Longitude": -84.411102,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "11/17/2020",
    "Project Owner/Name": "Project Fulton 2 -- Microsoft",
    "Address": "Ben Hill Road",
    "City": "East Point",
    "State": "GA",
    "Commission District": "6-Carn",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Data center",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 420000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 17128777,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 20,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution February 2021",
    "Other": "Corporate data center. Originally called Project Fulton without a location in October 2020. Brought back before the board in November. Final location and tax savings determined in February 2021.",
    "Approval": "Unanimous",
    "Latitude": 33.677637,
    "Longitude": -84.466536,
    "Accuracy Score": 1,
    "Accuracy Type": "street_center"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "11/17/2020",
    "Project Owner/Name": "Project Fulton 1 -- Microsoft",
    "Address": "Williams Road at Johnson Road and Tatum Road",
    "City": "Palmetto",
    "State": "GA",
    "Commission District": "6-Carn",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Data center",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 420000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 14554385,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 20,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Final Resolution November 2020",
    "Other": "Corporate data center. Originally called Project Fulton without a location in October 2020. Brought back before the board in November.",
    "Approval": "Unanimous",
    "Latitude": 33.52028,
    "Longitude": -84.623347,
    "Accuracy Score": 1,
    "Accuracy Type": "intersection"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "12/8/2020",
    "Project Owner/Name": "272 Ponce LLC -- Capital City Real Estate",
    "Address": "264-294 Ponce de Leon Avenue NE",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "4-Hall",
    "North I-20/South I-20 or Beltline": "North",
    "Project type": "Mixed-use office and retail",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 40000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1802504,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 200,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Induced December 2020",
    "Other": "Seven-story medical office building on top of a discount grocery store.",
    "Approval": "Three opposed Tidwell, Broadbent, Lamont",
    "Latitude": 33.772871,
    "Longitude": -84.378009,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2020,
    "Date of initial or final approval": "12/8/2020",
    "Project Owner/Name": "HIP I-85 South",
    "Address": "8396 Tatum Road",
    "City": "Palmetto",
    "State": "GA",
    "Commission District": "6-Carn",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 30000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1190376,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 200,
    "TAD": "No",
    "CID": "No",
    "Status": "Induced December 2020",
    "Other": "Speculative two-building industrial project of a combined 455,000 sf. Developer cited $1,350,000 in extraordinary costs for 4,000 feet of sewer and 1,900 feet of sidewalks.",
    "Approval": "Unanimous",
    "Latitude": 33.530633,
    "Longitude": -84.640133,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation"
  },
  {
    "Year": 2021,
    "Date of initial or final approval": "1/26/2021",
    "Project Owner/Name": "BI Developer-Palmetto LLC",
    "Address": "Bowen Road at Tatum Road",
    "City": "Palmetto",
    "State": "GA",
    "Commission District": "6-Abdur-Rahman",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 30670000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 966295,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": "",
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": 200,
    "TAD": "No",
    "CID": "No",
    "Status": "Induced January 2021",
    "Other": "Speculative warehouse for e-commerce useers or light industrial. Site work includes nearly 3,000 feet of road extension to Bowen Road, water and sewer improvements and \"challenging topography.",
    "Approval": "Two oppose Tidwell and Metze",
    "Latitude": 33.53556525,
    "Longitude": -84.64242364,
    "Accuracy Score": 0.51,
    "Accuracy Type": "intersection"
  },
  {
    "Year": 2021,
    "Date of initial or final approval": "2/18/2021",
    "Project Owner/Name": "Project Olympus -- PAC Worldwide Corporation",
    "Address": "4900 Stonewall Tell Road",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Abdur-Rahman",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 34675000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 1619908,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 399,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Induced February 2021",
    "Other": "Warehouse in Union City. In April 2021 identified as PAC Worldwide. Bond amount reduced to $34,675,000",
    "Approval": "Unanimous",
    "Latitude": 33.621977,
    "Longitude": -84.559987,
    "Accuracy Score": 0.7,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2021,
    "Date of initial or final approval": "3/23/2021",
    "Project Owner/Name": "SCP Hapeville",
    "Address": "397 North Central Avenue",
    "City": "Hapeville",
    "State": "GA",
    "Commission District": "6-Abdur-Rahman",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Mixed-use residential, retail and office",
    "Workforce Units": "None Listed",
    "Affordable Units": "None listed",
    "Bond Value": 53403000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 2565586,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 123,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Induced March 2021",
    "Other": "A mixed-use apartment development with 284 rental units, 24 rental townhouses, 5,000 sf of retail space and 20,000 sf of office space. No affordable or workforce housing mentioned.",
    "Approval": "Unanimous",
    "Latitude": 33.654885,
    "Longitude": -84.401823,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2021,
    "Date of initial or final approval": "5/18/2021",
    "Project Owner/Name": "Fairfield Piedmont",
    "Address": "1944 Piedmont Circle",
    "City": "Atlanta",
    "State": "GA",
    "Commission District": "3-Morris",
    "North I-20/South I-20 or Beltline": "North (Beltline)",
    "Project type": "Apartments",
    "Workforce Units": 59,
    "Affordable Units": "None Listed",
    "Bond Value": 100000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 4488842,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 10,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "Beltline",
    "CID": "No",
    "Status": "Induced May 2021",
    "Other": "392-unit apartment complex in a former 1960s-era motel. 59 workforce units at 80% AMI.",
    "Approval": "One abstained Tidwell",
    "Latitude": 33.811529,
    "Longitude": -84.367875,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop"
  },
  {
    "Year": 2021,
    "Date of initial or final approval": "5/18/2021",
    "Project Owner/Name": "Project Dash -- ASOS",
    "Address": "4505 Derrick Industrial Parkway",
    "City": "Union City",
    "State": "GA",
    "Commission District": "6-Abdur-Rahman",
    "North I-20/South I-20 or Beltline": "South",
    "Project type": "Industrial/warehouse",
    "Workforce Units": "N/A",
    "Affordable Units": "N/A",
    "Bond Value": 150000000,
    "Abatement or other": "Abatement",
    "DAFC estimated abatement value": 5202566,
    "AJC estimate of abatement value if none provided": "",
    "Est. Full-time jobs created if for a tenant": 20,
    "Claimed FT office jobs spec": "",
    "Claimed industrial jobs spec": "",
    "TAD": "No",
    "CID": "No",
    "Status": "Induced May 2021",
    "Other": "Project Dash, ASOS, is an existing warehouse tenant. The e-commerce seller of apparel is looking to expand its current operations with $123 million in new equipment and automation. The company would add 20 workers to their 1,000 employees. Project is allegedly competitive with Arizona or Nevada.",
    "Approval": "Unanimous",
    "Latitude": 33.62913,
    "Longitude": -84.582724,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop"
  }
]

init();